name: Publish to nuget

on: workflow_dispatch

jobs:
    publish_package:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            # -
            #     name: Setup dotnet
            #     uses: actions/setup-dotnet@v4
            #     with:
            #         dotnet-version: '9.x'
            -
                name: Build project
                run: dotnet build src/SqlForgery/SqlForgery.csproj -c Release
            -
                name: Create nupkg
                run: dotnet pack --output .output
            -
                name: Publish to nuget
                env:
                    NUGET_API_KEY: $${{ secrets.NUGET_API_KEY }}
                run: |
                    dotnet nuget push .output/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json                    