name: Publish to nuget

on: workflow_dispatch

jobs:
    publish_package:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            -
                name: Create nupkg
                run: dotnet pack --output .output -c Release
            -
                name: Publish to nuget
                env:
                    NUGET_API_KEY: $${{ secrets.NUGET_API_KEY }}
                run: |
                    dotnet nuget push .output/*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json                    